# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setEnabled(False)
        self.saveButton.setGeometry(QtCore.QRect(690, 530, 81, 22))
        self.saveButton.setObjectName("saveButton")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 801, 521))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 10, 791, 157))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.locationLabel = QtWidgets.QLabel(self.formLayoutWidget)
        self.locationLabel.setObjectName("locationLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.locationLabel)
        self.locationComboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.locationComboBox.setObjectName("locationComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.locationComboBox)
        self.labelLuc = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelLuc.setObjectName("labelLuc")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelLuc)
        self.spinBoxLuc = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxLuc.setMaximum(677215)
        self.spinBoxLuc.setObjectName("spinBoxLuc")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBoxLuc)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 791, 321))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.labelCharacter1Name = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.labelCharacter1Name.setObjectName("labelCharacter1Name")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelCharacter1Name)
        self.c1NameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.c1NameLineEdit.setObjectName("c1NameLineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.c1NameLineEdit)
        self.labelCurrentHpChar1 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.labelCurrentHpChar1.setObjectName("labelCurrentHpChar1")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelCurrentHpChar1)
        self.labelMaxHpChar1 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.labelMaxHpChar1.setObjectName("labelMaxHpChar1")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelMaxHpChar1)
        self.spinBoxCurrentHpChar1 = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.spinBoxCurrentHpChar1.setMaximum(999)
        self.spinBoxCurrentHpChar1.setObjectName("spinBoxCurrentHpChar1")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBoxCurrentHpChar1)
        self.spinBoxMaxHpChar1 = QtWidgets.QSpinBox(self.formLayoutWidget_2)
        self.spinBoxMaxHpChar1.setMaximum(999)
        self.spinBoxMaxHpChar1.setObjectName("spinBoxMaxHpChar1")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBoxMaxHpChar1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 791, 311))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.labelCharacter2Name = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.labelCharacter2Name.setObjectName("labelCharacter2Name")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelCharacter2Name)
        self.c2NameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.c2NameLineEdit.setObjectName("c2NameLineEdit")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.c2NameLineEdit)
        self.labelCurrentHpChar2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.labelCurrentHpChar2.setObjectName("labelCurrentHpChar2")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelCurrentHpChar2)
        self.labelMaxHpChar2 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.labelMaxHpChar2.setObjectName("labelMaxHpChar2")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelMaxHpChar2)
        self.spinBoxCurrentHpChar2 = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.spinBoxCurrentHpChar2.setMaximum(999)
        self.spinBoxCurrentHpChar2.setObjectName("spinBoxCurrentHpChar2")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBoxCurrentHpChar2)
        self.spinBoxMaxHpChar2 = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        self.spinBoxMaxHpChar2.setMaximum(999)
        self.spinBoxMaxHpChar2.setObjectName("spinBoxMaxHpChar2")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBoxMaxHpChar2)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.tab_4)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, 791, 361))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.labelCharacter3Name = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.labelCharacter3Name.setObjectName("labelCharacter3Name")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelCharacter3Name)
        self.c3NameLineEdit = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.c3NameLineEdit.setObjectName("c3NameLineEdit")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.c3NameLineEdit)
        self.labelCurrentHpChar3 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.labelCurrentHpChar3.setObjectName("labelCurrentHpChar3")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelCurrentHpChar3)
        self.labelMaxHpChar3 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.labelMaxHpChar3.setObjectName("labelMaxHpChar3")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelMaxHpChar3)
        self.spinBoxCurrentHpChar3 = QtWidgets.QSpinBox(self.formLayoutWidget_4)
        self.spinBoxCurrentHpChar3.setMaximum(999)
        self.spinBoxCurrentHpChar3.setObjectName("spinBoxCurrentHpChar3")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBoxCurrentHpChar3)
        self.spinBoxMaxHpChar3 = QtWidgets.QSpinBox(self.formLayoutWidget_4)
        self.spinBoxMaxHpChar3.setMaximum(999)
        self.spinBoxMaxHpChar3.setObjectName("spinBoxMaxHpChar3")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.spinBoxMaxHpChar3)
        self.tabWidget.addTab(self.tab_4, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 19))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName("actionSave")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Seiken Densetsu 3 Save Editor"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.locationLabel.setText(_translate("MainWindow", "Location"))
        self.labelLuc.setText(_translate("MainWindow", "Luc"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "General"))
        self.labelCharacter1Name.setText(_translate("MainWindow", "Name"))
        self.labelCurrentHpChar1.setText(_translate("MainWindow", "Current HP"))
        self.labelMaxHpChar1.setText(_translate("MainWindow", "Max HP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Character 1"))
        self.labelCharacter2Name.setText(_translate("MainWindow", "Name"))
        self.labelCurrentHpChar2.setText(_translate("MainWindow", "Current HP"))
        self.labelMaxHpChar2.setText(_translate("MainWindow", "Max HP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Character 2"))
        self.labelCharacter3Name.setText(_translate("MainWindow", "Name"))
        self.labelCurrentHpChar3.setText(_translate("MainWindow", "Current HP"))
        self.labelMaxHpChar3.setText(_translate("MainWindow", "Max HP"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Character 3"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))

