name: Python application

on: [push]

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]
          include:
            - os: ubuntu-latest
              ARTIFACT_NAME: sd3save_editor_linux
            - os: windows-latest
              ARTIFACT_NAME: sd3save_editor_windows

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install poetry pyinstaller
        poetry install
      shell: bash
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run pytest
      run: poetry run pytest
    - name: Build executable
      run: make
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.ARTIFACT_NAME}}
        path: dist/sd3save_editor*
